### ISSUE TITLE
no record of data monitoring after change hostname using TEMBOARD_HOSTNAME

### ISSUE THREAD

**Issue by fathoniinsansilmi** [dalibo/temboard#1276]
hi dalibo, my temboard UI doesnt show any record of data monitoring form past after change hostname using temboard_hostname, monitoring just shown the newest data monitoring after we changed the temboard hostname, we changed it in conf and also the evironmet variable, we need ur help

temboard ui v8.0
temboard agent v7.11

![image](https://github.com/dalibo/temboard/assets/89531166/279f6ed0-d4b9-4b77-b7d5-3a1941cb6e7a)

**Comment by fathoniinsansilmi** [comment]
![image](https://github.com/dalibo/temboard/assets/89531166/40850ead-4eaa-490f-8a39-7392da52b22b)

after we changed it back to original server hostname , the past record monitoring was shown but it doesnt continue showing the newest data record

**Comment by bersace** [comment]
hi @fathoniinsansilmi . Yes, there is no *renaming* of hostname in temBoard. It's like if they are two different machines;

i suggest to keep this open as a feature request.
We could implement hostname historization in UI so that UI queries metrics for all hostnames.

As a workaround you may instanciate another agent with the old hostname hardcoded in configuration.
This way, you can view old metrics with this agent.
Still they wont be on the same page.

cc @daamien for the feature request.

**Comment by fathoniinsansilmi** [comment]
hi @bersace, so that mean we cant use two hostname that we used before and the newest one for the future? coz we had rename it back to the original but the matrix diagram or data record monitoring is stoping..
