### ISSUE TITLE
the file ``share/supervision.sql`` is missing

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#13]
I can't find the init SQL script for the supervision plugin : 

As explain here:
http://temboard.readthedocs.io/en/latest/temboard-repository-setup/#installation

The file should be in ``share/supervision.sql``

**Comment by rjuju** [comment]
The file is located in `temboardui/plugins/supervision/sql/supervision.sql` in the git repository.  I'm not sure if the packages moves it in `/usr/share/temboard` or not.

**Comment by julmon** [comment]
`setuptools` module is not able to install data files outside from the python package (/usr/share in that case) when installing `temboard` from sources, that's why I've updated the documentation in my last 2 commits and write down that we need to copy these files manually in `/usr/share/temboard` and `/usr/share/temboard-agent`.
