### ISSUE TITLE
Upgrading from 0.0.1 to Latest for both Server and Agent

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#197]
Can you recommend a process for this so existing data can be preserved, or do we need to do a full wipe and reinstall?

**Current:**

``` console
# yum list installed | grep temboard
python-certifi.noarch         2016.2.28-1.el7.centos  @temboard-rhel7
python-tornado.x86_64         4.3-1.el7.centos        @temboard-rhel7
temboard.noarch               0.0.1-10.el7.centos     @temboard-rhel7
temboard-agent.noarch         0.0.1-10.el7.centos     @temboard-rhel7
```

**We need to upgrade to:**

temboard (1.0a3)
temboard-agent (0) ---- latest commit - dalibo/temboard-agent@4d70d9d

**Comment by bersace** [comment]
@bsislow This is correct. You can ignore temboard* rpm. They are outdated. We are about to release 1.0 to PyPI and then review our repositories.

**Comment by bsislow** [comment]
I am not following - what is "correct?" I am asking what the process is to upgrade...

**Comment by bersace** [comment]
@bsislow sorry. I mean you should not have to upgrade, just install latest version.

I uploaded 1.0 in PyPI so that you don't need `--pre`.

I updated installation guide at http://temboard.readthedocs.io/en/latest/installation/ .

The RPM repository is outdated and should not be used. You can remove it from your installation. sorry for the lack of consistency ! :/

**Comment by dgiffin** [comment]
I'm happy to open a new issue, but I need guidance on upgrading from version 0 to version 1.0, including the repository - I've checked the docs but can't see anything about upgrading. I would rather not reinstall and lose our historical data if possible!
