### ISSUE TITLE
Plan ?

### ISSUE THREAD

**Issue by blogh** [dalibo/temboard#25]
Hi, 

I think this project is really cool. 
But I am wondering  what is next ? Do you have a plan in mind ?

Benoit

**Comment by julmon** [comment]
Hi,

Yes, we have a plan, here it is:

1. I'm currently refactoring the way how temboard stores supervision data in its repository. It's take too much space (10MB / instance / day) and won't scale. With this new way, this rate will fall to 1MB / instance / day. I hope to commit my work in the next few days.

2. We plan to add an automated alerting system based on supervision data. The design of this mechanism is done and I will start the implementation right after the previous item.

3. Release the first version: 1.0

4. Temboard UI rewriting

5. Add PITR Backup plugin

6. Add pgbouncer plugin

7. Add Streaming repl. plugin

8. Add maintenance (vacuum/analyze/bloat analysis) plugin

Regards,

**Comment by blogh** [comment]
Cool, How can i get involved ? 

Right now. I do it on my spare time so I don't think I can undertake huge things especially is your schedule is tight. But if I can help... 

(btw i am in Nantes)

**Comment by daamien** [comment]
Hi !

Thanks for your interest in the project ! A few days ago, we discussed about maintaining a TO DO list with a tag called "junior job" or "starter task" so that people can get involved more easily. I think we'll try to push it very soon publicly here !

Btw I'll be in Nantes on Monday, if you have time we can have a beer in the evening ?
