### ISSUE TITLE
 [temboardui] ERROR: FATAL: [Errno 98] Address already in use. Quit

### ISSUE THREAD

**Issue by seadba** [dalibo/temboard#280]
hello, i installed server and agent on same machine - on startup for temboard i get following

2018-03-07 15:30:01,473 temboard[45791]: [temboardui] INFO: Starting task manager.
2018-03-07 15:30:01,478 temboard[45791]: [temboardui] ERROR: FATAL: [Errno 98] Address already in use. Quit

i dont see anything on 8888 
[temboard.log](https://github.com/dalibo/temboard/files/1790761/temboard.log)

log attatched

**Comment by julmon** [comment]
Hello,

This is probably due to `temboard` and `temboard-agent` are using the same dir. path as their own `home` dir.

Could you try to change the value of parameter `home` in both configuration files ?

For `temboard-agent`:
```ini
[temboard]
...
home=/var/lib/temboard-agent
```

For `temboard`:
```ini
[temboard]
...
home=/var/lib/temboard
```

Be sure that these paths exist and are writable respectively by `postgres` (for the agent) and `temboard` (for the UI).

Regards,

**Comment by seadba** [comment]
hello, thanks for the response - i dont see a home var in agent.conf

-bash-4.2$ grep -i home  /etc/temboard-agent/temboard-agent.conf
-bash-4.2$

[temboard@linux1 temboard]$ grep -i home /etc/temboard/temboard.conf
home = /tmp

**Comment by seadba** [comment]
sorry, are these parameters that have to be manually added or is the config file incorrect?
