### ISSUE TITLE
No data available on monitoring metrics 

### ISSUE THREAD

**Issue by phoenixhel** [dalibo/temboard#928]
Hello Everyone,

I've an issue with temboard metrics. Data can't be shown on monitoring metrics, it's only shows that no data is available.

Best regards,

**Comment by bersace** [comment]
Hi @phoenixhel , thanks for reaching.

Do you have some errors in logs ?

**Comment by ced75** [comment]
Hi,

I face exactly the same problem since last temboard 7.8 upgrade.
But there is no particular error in temboard-agent logs.

On Temboard server, I get the following errors:

>nov. 15 11:39:46 inv-monitor env[31298]: Error while fetching statements from instance: pg_stat_statements not enabled on database postgres
nov. 15 11:39:46 inv-monitor env[31298]: HTTP Error 404: Not Found
nov. 15 11:39:46 inv-monitor env[31298]: Traceback (most recent call last):
nov. 15 11:39:46 inv-monitor env[31298]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/statements/__init__.py", line 825, in pull_data_for_instance
nov. 15 11:39:46 inv-monitor env[31298]:     headers=headers,
nov. 15 11:39:46 inv-monitor env[31298]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/temboardclient.py", line 86, in temboard_request
nov. 15 11:39:46 inv-monitor env[31298]:     handle = url_opener.open(request)
nov. 15 11:39:46 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 435, in open
nov. 15 11:39:46 inv-monitor env[31298]:     response = meth(req, response)
nov. 15 11:39:46 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
nov. 15 11:39:46 inv-monitor env[31298]:     'http', request, response, code, msg, hdrs)
nov. 15 11:39:46 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 473, in error
nov. 15 11:39:46 inv-monitor env[31298]:     return self._call_chain(*args)
nov. 15 11:39:46 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
nov. 15 11:39:46 inv-monitor env[31298]:     result = func(*args)
nov. 15 11:39:46 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
nov. 15 11:39:46 inv-monitor env[31298]:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
nov. 15 11:39:46 inv-monitor env[31298]: HTTPError: HTTP Error 404: Not Found
nov. 15 11:39:47 inv-monitor env[31298]: Error while fetching statements from instance: ERREUR:  la relation « pg_stat_statements » n'existe pas
nov. 15 11:39:47 inv-monitor env[31298]: LINE 5: FROM pg_stat_statements pgss
nov. 15 11:39:47 inv-monitor env[31298]:              ^
nov. 15 11:39:47 inv-monitor env[31298]: HTTP Error 500: Internal Server Error
nov. 15 11:39:47 inv-monitor env[31298]: Traceback (most recent call last):
nov. 15 11:39:47 inv-monitor env[31298]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/statements/__init__.py", line 825, in pull_data_for_instance
nov. 15 11:39:47 inv-monitor env[31298]:     headers=headers,
nov. 15 11:39:47 inv-monitor env[31298]:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/temboardclient.py", line 86, in temboard_request
nov. 15 11:39:47 inv-monitor env[31298]:     handle = url_opener.open(request)
nov. 15 11:39:47 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 435, in open
nov. 15 11:39:47 inv-monitor env[31298]:     response = meth(req, response)
nov. 15 11:39:47 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
nov. 15 11:39:47 inv-monitor env[31298]:     'http', request, response, code, msg, hdrs)
nov. 15 11:39:47 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 473, in error
nov. 15 11:39:47 inv-monitor env[31298]:     return self._call_chain(*args)
nov. 15 11:39:47 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
nov. 15 11:39:47 inv-monitor env[31298]:     result = func(*args)
nov. 15 11:39:47 inv-monitor env[31298]:   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
nov. 15 11:39:47 inv-monitor env[31298]:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
nov. 15 11:39:47 inv-monitor env[31298]: HTTPError: HTTP Error 500: Internal Server Error

**Comment by bersace** [comment]
@ced75 pg_stat_statement is not enabled on monitored PostgreSQL instance, Could you ensure the configuration is ok and extension is created ? see https://www.postgresql.org/docs/current/pgstatstatements.html for details on how to enable this extension.

**Comment by ced75** [comment]
Done, but the metrics remain empty with "No data available".

**Comment by bersace** [comment]
@ced75 do you have other errors in agent and UI logs ?

**Comment by ced75** [comment]
Unfortunately, no.
Neither in UI logs, nor in agent logs.
Sorry.

**Comment by wahyubudiman** [comment]
i have same issue, any update for this ?

**Comment by bersace** [comment]
Is this related to #941 ?

**Comment by ced75** [comment]
Unfortunately, no. We did not notice any crash/reboot. Just an upgrade.

**Comment by bersace** [comment]
@ced75 Could you upgrade UI to 7.9 ? It has improved message logging for such issues.

**Comment by ced75** [comment]
Hi,

I get a list of errors on UI server when I try to upgrade the DB as explained in documentation.
The service is stopped, I performed the apt package upgrade, and when I try to apply:
`sudo -u temboard temboard-migratedb upgrade`

I get this list of errors:

>  INFO: Starting temboard-migratedb 7.9.
>  INFO: Found config file /etc/temboard/temboard.conf.
> /usr/lib/temboard/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
>  INFO: Context impl PostgresqlImpl.
>  INFO: Will assume transactional DDL.
>  INFO: Running upgrade 67f52879da15 -> 55ab971bde17, metrics-archive-deadlock
> ERROR: Unhandled error:
> ERROR: Traceback (most recent call last):
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
> ERROR:     retcode = self.main(argv, environ)
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 66, in main
> ERROR:     command(args)
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 82, in command_upgrade
> ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/command.py", line 294, in upgrade
> ERROR:     script.run_env()
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 490, in run_env
> ERROR:     util.load_python_file(self.dir, "env.py")
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
> ERROR:     module = load_module_py(module_id, path)
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/compat.py", line 219, in load_module_py
> ERROR:     mod = imp.load_source(module_id, path, fp)
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
> ERROR:     run_migrations_online()
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online
> ERROR:     context.run_migrations()
> ERROR:   File "<string>", line 8, in run_migrations
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
> ERROR:     self.get_context().run_migrations(**kw)
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
> ERROR:     step.migration_fn(**kw)
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/versions/20211112_2d55ab971bde17_metrics_archive_deadlock.py", line 30, in upgrade
> ERROR:     op.get_bind().execute(sqlfile(name))
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1289, in execute
> ERROR:     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
> ERROR:     self, multiparams, params, execution_options
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _execute_clauseelement
> ERROR:     cache_hit=cache_hit,
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
> ERROR:     e, statement, parameters, cursor, context
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2027, in _handle_dbapi_exception
> ERROR:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1803, in _execute_context
> ERROR:     cursor, statement, parameters, context
> ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
> ERROR:     cursor.execute(statement, parameters)
> ERROR: ProgrammingError: (psycopg2.ProgrammingError) ERREUR:  doit être le propriétaire de la fonction history_tables
> ERROR: 
> ERROR: [SQL: SET search_path TO monitoring, public;
> ERROR: 
> ERROR: CREATE OR REPLACE FUNCTION archive_current_metrics(table_name TEXT, record_type TEXT, query TEXT) RETURNS TABLE(tblname TEXT, nb_rows INTEGER)
> ERROR: LANGUAGE plpgsql
> ERROR: AS $$
> ERROR: DECLARE
> ERROR:   v_table_current TEXT;
> ERROR:   v_table_history TEXT;
> ERROR:   v_query TEXT;
> ERROR:   i INTEGER;
> ERROR: BEGIN
> ERROR:   v_table_current := table_name || '_current';
> ERROR:   v_table_history := table_name || '_history';
> ERROR:   -- Lock _current table to prevent concurrent updates
> ERROR:   EXECUTE 'LOCK TABLE ' || v_table_current || ' IN SHARE MODE NOWAIT';
> ERROR:   v_query := replace(query, '#history_table#', v_table_history);
> ERROR:   v_query := replace(v_query, '#current_table#', v_table_current);
> ERROR:   v_query := replace(v_query, '#record_type#', record_type);
> ERROR:   -- Move data into _history table
> ERROR:   EXECUTE v_query;
> ERROR:   GET DIAGNOSTICS i = ROW_COUNT;
> ERROR:   -- Truncate _current table
> ERROR:   EXECUTE 'TRUNCATE '||v_table_current;
> ERROR:   -- Return each history table name and the number of rows inserted
> ERROR:   RETURN QUERY SELECT v_table_history, i;
> ERROR: END;
> ERROR: $$;
> ERROR: 
> ERROR: DROP FUNCTION IF EXISTS history_tables();
> ERROR: 
> ERROR: CREATE OR REPLACE FUNCTION aggregate_data_single(table_name TEXT, record_type TEXT, query TEXT) RETURNS TABLE(tblname TEXT, nb_rows INTEGER)
> ERROR: LANGUAGE plpgsql
> ERROR: AS $$
> ERROR: DECLARE
> ERROR:   t JSON;
> ERROR:   v_agg_periods TEXT[] := array['30m', '6h'];
> ERROR:   v_agg_table TEXT;
> ERROR:   i_period TEXT;
> ERROR:   v_query TEXT;
> ERROR:   i INTEGER;
> ERROR: BEGIN
> ERROR:   -- Build and run 'aggregate' query for type of metric.
> ERROR:   FOREACH i_period IN ARRAY v_agg_periods LOOP
> ERROR:     v_agg_table := table_name || '_' || i_period || '_current';
> ERROR:     v_query := replace(query, '#agg_table#', v_agg_table);
> ERROR:     v_query := replace(v_query, '#interval#', i_period);
> ERROR:     v_query := replace(v_query, '#record_type#', record_type);
> ERROR:     v_query := replace(v_query, '#name#', table_name);
> ERROR:     EXECUTE v_query;
> ERROR:     GET DIAGNOSTICS i = ROW_COUNT;
> ERROR:     RETURN QUERY SELECT v_agg_table, i;
> ERROR:   END LOOP;
> ERROR: END;
> ERROR: $$;
> ERROR: 
> ERROR: DROP FUNCTION IF EXISTS aggregate_data();
> ERROR: ]
> ERROR: (Background on this error at: https://sqlalche.me/e/14/f405)
> ERROR: temboardui version is 7.9.
> ERROR: This is a bug!
> ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!

This seems to be related to the objects owner in temboard DB, isn't it?

**Comment by ced75** [comment]
When I reinstalled temboard UI on the monitoring server, I used the standard procedure described in the documentation.
In the temboard database, it is "postgres" user which is owner of all objects.

I understand better the error message when the upgradedb command is launched as temboard user, if the script launches the upgrade in PostgreSQL as "temboard"...
Is it the case?

**Comment by bersace** [comment]
I confirm the bug.

**Comment by bersace** [comment]
@ced75 you need to fix ownership of temboard database objects to temboard.

**Comment by ced75** [comment]
Have you any procedure to achieve this. I can't apply a "reassign owned by postgres to temboard;" because of system objects that can't by reassigned.
There are many schemas and objects inside schemas.

**Comment by ced75** [comment]
OK, after having applied https://github.com/bersace/temboard/blob/repository/share/reassign.sql, the database upgrade worked and the temboard service is now started again.
And now, with temboard 7.9 UI and agents, monitoring metrics are back.

Thanks very much!
